### ISSUE TITLE
Post Processing doesn't render in 2022

### ISSUE THREAD

**Issue by Neill3d** [Neill3d/OpenMoBu#7]
feedback from a compiled version to 2022 - I'm trying to render in 2022 with post-processing and so far it doesn't appear in the rendered frames

**Comment by boiteapurain** [comment]
Hello,,

First I would like to say thank you for your great work.
I was wondering if your fix is available for 2023, because I have a crash when i try to render with processing on mobu 2023.
I have no experience on this software I am not sure if you your compile version for 2022 can be applied  to newest version.

Best Regards

Mathieu

**Comment by Neill3d** [comment]
Hello Mathieu, how did you get your 2023 plugin ? from repository binaries ?
btw, I also quite often avaliable on discord, feel free to join if you would like to https://discord.gg/ManUkNwE

**Comment by boiteapurain** [comment]
Thanks for the discord,

I grab your 2023 repository binaries. 
I was wondering if compiling my self you plugins can solve the post process render issue for mobu 2023 ?

**Comment by Neill3d** [comment]
year, this summer I had a session with Les Androids for fixing rendering for 2023, so it's quite interesting that you have crash. either the binary is not the latest one and build the source could help or it's some new bug that other users didn't discover yet.
 I will write on discord in openmobu channel about testing
